name: busco_phylogenomics
channels:
  - conda-forge
  - bioconda
dependencies:
  - amas=1.0
  - biopython
  - busco=5.8.3
  - ca-certificates
  - iqtree=2.4.0
  - mafft
  - python>=3.12
  - tqdm
  - trimal
