name: busco_phylogenomics
channels:
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - _x86_64-microarch-level=4
  - alsa-lib=1.2.14
  - amas=1.0
  - augustus=3.5.0
  - bamtools=2.5.3
  - bbmap=39.28
  - binutils_impl_linux-64=2.44
  - biopython=1.85
  - blast=2.16.0
  - boost-cpp=1.85.0
  - brotli-python=1.1.0
  - busco=5.8.3
  - bwidget=1.10.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cairo=1.18.4
  - cdbtools=0.99
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.4.2
  - clustalw=2.1
  - colorama=0.4.6
  - curl=8.14.1
  - dendropy=5.0.8
  - diamond=2.1.13
  - dnspython=2.7.0
  - entrez-direct=22.4
  - fasttree=2.1.11
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.13.3
  - fribidi=1.0.10
  - gawk=5.3.1
  - gcc_impl_linux-64=15.1.0
  - gfortran_impl_linux-64=15.1.0
  - giflib=5.2.2
  - gmp=6.3.0
  - graphite2=1.3.14
  - gsl=2.7
  - gxx_impl_linux-64=15.1.0
  - h2=4.2.0
  - harfbuzz=11.3.3
  - hmmer=3.4
  - hpack=4.1.0
  - htslib=1.22
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - iqtree=2.4.0
  - jsoncpp=1.9.6
  - kernel-headers_linux-64=4.18.0
  - keyutils=1.6.1
  - krb5=1.21.3
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libamd=3.3.3
  - libasprintf=0.25.1
  - libblas=3.9.0
  - libboost=1.85.0
  - libboost-devel=1.85.0
  - libboost-headers=1.85.0
  - libbtf=2.3.2
  - libcamd=3.3.3
  - libcblas=3.9.0
  - libccolamd=3.3.4
  - libcholmod=5.3.1
  - libcolamd=3.3.4
  - libcups=2.3.3
  - libcurl=8.14.1
  - libcxsparse=4.4.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=15.1.0
  - libgcc-ng=15.1.0
  - libgettextpo=0.25.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.2
  - libgomp=15.1.0
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - libklu=2.3.5
  - liblapack=3.9.0
  - libldl=3.3.2
  - liblzma=5.8.1
  - liblzma-devel=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopenssl-static=3.5.1
  - libparu=1.0.0
  - libpng=1.6.50
  - librbio=4.3.4
  - libsanitizer=15.1.0
  - libspex=3.2.3
  - libspqr=4.3.4
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=15.1.0
  - libstdcxx-ng=15.1.0
  - libsuitesparseconfig=7.10.1
  - libtiff=4.7.0
  - libumfpack=6.3.5
  - libunistring=0.9.10
  - libuuid=2.38.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - lp_solve=5.5.2.11
  - mafft=7.526
  - make=4.4.1
  - metaeuk=7.bba0d80
  - metis=5.1.0
  - miniprot=0.18
  - mpfr=4.2.1
  - mpi=1.0
  - muscle=3.8.1551
  - mysql-connector-c=6.1.11
  - ncbi-vdb=3.2.1
  - ncurses=6.5
  - numpy=2.3.2
  - openjdk=23.0.2
  - openmpi=4.1.6
  - openssl=3.5.1
  - pandas=2.3.1
  - pango=1.56.4
  - pasta=1.9.3
  - pcre=8.45
  - pcre2=10.45
  - perl=5.32.1
  - perl-app-cpanminus=1.7048
  - perl-archive-tar=3.04
  - perl-carp=1.50
  - perl-class-method-modifiers=2.13
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-constant=1.33
  - perl-dbi=1.643
  - perl-encode=3.21
  - perl-exporter=5.74
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.70
  - perl-file-path=2.18
  - perl-file-temp=0.2304
  - perl-file-which=1.24
  - perl-inc-latest=0.500
  - perl-io-compress=2.201
  - perl-io-zlib=1.15
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-module-build=0.4234
  - perl-moo=2.005004
  - perl-parallel-forkmanager=2.03
  - perl-parent=0.243
  - perl-pathtools=3.75
  - perl-role-tiny=2.002004
  - perl-scalar-list-utils=1.70
  - perl-storable=3.15
  - perl-sub-quote=2.006006
  - perl-test-fatal=0.016
  - perl-try-tiny=0.31
  - perl-types-serialiser=1.01
  - perl-yaml=1.30
  - pip=25.2
  - pixman=0.46.4
  - prank=170427
  - prodigal=2.6.3
  - pthread-stubs=0.4
  - pycparser=2.22
  - pymongo=4.13.2
  - pysocks=1.7.1
  - python=3.12.11
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.12
  - pytz=2025.2
  - r-base=4.4.3
  - r-cli=3.6.5
  - r-colorspace=2.1_1
  - r-crayon=1.5.3
  - r-ellipsis=0.3.2
  - r-fansi=1.0.6
  - r-farver=2.1.2
  - r-ggplot2=3.5.2
  - r-glue=1.8.0
  - r-gtable=0.3.6
  - r-isoband=0.2.7
  - r-labeling=0.4.3
  - r-lattice=0.22_7
  - r-lifecycle=1.0.4
  - r-magrittr=2.0.3
  - r-mass=7.3_64
  - r-matrix=1.7_3
  - r-mgcv=1.9_3
  - r-munsell=0.5.1
  - r-nlme=3.1_168
  - r-pillar=1.11.0
  - r-pkgconfig=2.0.3
  - r-r6=2.6.1
  - r-rcolorbrewer=1.1_3
  - r-rlang=1.1.6
  - r-scales=1.4.0
  - r-tibble=3.3.0
  - r-utf8=1.2.6
  - r-vctrs=0.6.5
  - r-viridislite=0.4.2
  - r-withr=3.0.2
  - raxml=8.2.13
  - readline=8.2
  - requests=2.32.4
  - rpsbproc=0.5.0
  - samtools=1.22
  - sed=4.9
  - sepp=4.5.5
  - setuptools=80.9.0
  - six=1.17.0
  - sniffio=1.3.1
  - sqlite=3.50.4
  - suitesparse=7.10.1
  - sysroot_linux-64=2.28
  - tar=1.35
  - tk=8.6.13
  - tktable=2.10
  - tqdm=4.67.1
  - trimal=1.5.0
  - tzdata=2025b
  - ucsc-fatotwobit=482
  - ucsc-twobitinfo=482
  - urllib3=2.5.0
  - wget=1.21.4
  - wheel=0.45.1
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxt=1.3.1
  - xorg-libxtst=1.2.5
  - xz=5.8.1
  - xz-gpl-tools=5.8.1
  - xz-tools=5.8.1
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
