name: busco_phylogenomics
channels:
  - conda-forge
  - bioconda
dependencies:
  - python[version='>=3.10']
  - biopython
  - ca-certificates
  - openssl
  - busco==5.8.3
  - mafft
  - trimal
  - iqtree==2.4.0
  - amas
  - tqdm
